name: CI

on:
  pull_request:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ['openjdk@1.17.0']
        scala: ['2.13.6']
        platform: ['JVM']
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v14
      with:
        java-version: ${{ matrix.java }}
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6.4
    - name: Run tests
      run: sbt test
